INSERT INTO CAR_RENTAL.USER_ROLE (ROLE)
VALUES ('ADMIN');
INSERT INTO CAR_RENTAL.USER_ROLE (ROLE)
VALUES ('CLIENT');

INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('BRONZE', 3.0);
INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('SILVER', 5.0);
INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('GOLD', 10.0);
INSERT INTO CAR_RENTAL.DISCOUNT_STATUS (STATUS, DISCOUNT)
VALUES ('BRILLIANT', 15.0);

INSERT INTO CAR_RENTAL.user_details(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER1', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.user_details(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER2', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.user_details(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER3', 'SHUMAHEROVICH', 'AA1111', 999);
INSERT INTO CAR_RENTAL.user_details(FIRST_NAME, LAST_NAME, PASSPORT_DATA, TOTAL_RENTAL_TIME)
VALUES ('SHUMAHER4', 'SHUMAHEROVICH', 'AA1111', 999);

INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, USER_DETAILS_ID)
VALUES ('MIKE', '$2a$12$aD3zBkGlAtwAHmcUravf2eUPokVFchcA0JlDQN.89lEE9AWxcAq0C', 'mike@google.com', 1);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, USER_DETAILS_ID)
VALUES ('TOM', '$2a$12$oatgfJyZKzY3TkBhD0riHeyQsREkeSBiKe7idkb4DL9JBF6oh63PS', 'tom@google.com', 2);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, USER_DETAILS_ID)
VALUES ('LIANA', '$2a$12$z7BYvMAHz9COF39c6pthc.cbBqtg.BR2TAEWH4.trEC8QK0XoCDMy', 'liana@google.com', 3);
INSERT INTO CAR_RENTAL.USER (USERNAME, PASSWORD, EMAIL, USER_DETAILS_ID)
VALUES ('JHON', '$2a$12$GFZXMACDCVELfF9Uyy1sdOQJ2xgeoyMtKR/1uLp8qI9xhGn819Cgi', 'jhon@google.com', 4);

INSERT INTO CAR_RENTAL.AUTHORITY (USERNAME, ROLE_ID)
VALUES ('MIKE', 1);
INSERT INTO CAR_RENTAL.AUTHORITY (USERNAME, ROLE_ID)
VALUES ('TOM', 1);
INSERT INTO CAR_RENTAL.AUTHORITY (USERNAME, ROLE_ID)
VALUES ('LIANA', 2);
INSERT INTO CAR_RENTAL.AUTHORITY (USERNAME, ROLE_ID)
VALUES ('JHON', 2);

INSERT INTO CAR_RENTAL.CAR_STATUS (STATUS)
VALUES ('READY');
INSERT INTO CAR_RENTAL.CAR_STATUS (STATUS)
VALUES ('BROKEN');
INSERT INTO CAR_RENTAL.CAR_STATUS (STATUS)
VALUES ('REPAIRING');

INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('WAITING FOR PAYMENT', 'ORDER IS WAITING FOR CLIENT''S PAYMENT.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('PAID', 'ORDER IS PAID AND WAITING FOR CONFIRMATION.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('CONFIRMED', 'ORDER IS CONFIRMED. CAR IS READY.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('COMPLETED', 'ORDER IS COMPLETED.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('DECLINED BY ADMIN', 'ORDER IS DECLINED BY ADMIN.');
INSERT INTO CAR_RENTAL.ORDER_STATUS (STATUS, DESCRIPTION)
VALUES ('CANCELED BY CLIENT', 'ORDER IS CANCELED BY CLIENT.');

INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR)
VALUES ('VOLKSWAGEN', 'POLO', 'SEDAN', 'PETROL', 1.6, 'MANUAL TRANSMISSION', 'REEF BLUE', 'GRAY');
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR)
VALUES ('VOLKSWAGEN', 'TAOS', 'CROSSOVER', 'PETROL', 2.0, 'AUTOMATIC TRANSMISSION', 'REEF BLUE', 'BLACK');
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR)
VALUES ('VOLKSWAGEN', 'TIGUAN', 'CROSSOVER', 'PETROL', 2.0, 'AUTOMATIC TRANSMISSION', 'SILK BLUE METALLIC', 'TAN');
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR)
VALUES ('NISSAN', 'JUKE', 'SUV', 'PETROL', 1.6, 'MANUAL TRANSMISSION', 'RED', 'BLACK');
INSERT INTO CAR_RENTAL.CAR_MODEL (BRAND_NAME, MODEL, BODY_TYPE, FUEL_TYPE, ENGINE_VOLUME, TRANSMISSION, BODY_COLOR,
                                  INTERIOR_COLOR)
VALUES ('NISSAN', 'X-TRAIL', 'CROSSOVER', 'DIESEL', 1.6, 'AUTOMATIC TRANSMISSION', 'RED', 'TAN');

INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('2911CC-7', 1, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('2912CC-7', 1, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('2922CC-7', 2, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('2930CC-7', 3, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('4089CC-7', 4, 1);
INSERT INTO CAR_RENTAL.CAR (STATE_NUMBER, CAR_MODEL_ID, CAR_STATUS_ID)
VALUES ('4054CC-7', 5, 1);